/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.BlackJackGameEngine;
import Model.BlackJackDeck;
import Model.Card;
import Model.Player;
import java.awt.Graphics;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalie
 */
public class BlackJackFrame extends javax.swing.JFrame {

    public static int currency;
    BlackJackGameEngine e;
    public int c = currency;
    
    static void startIt(Player player) {
//        System.out.println("FROM BLACKJACK FRAME : " + Player.currency);
        BlackJackFrame.main(null);
    }
    /**
     * Creates new form BlackJackFrame
     */
    public BlackJackFrame() {
        initComponents();
        JOptionPane.showMessageDialog(null, "Please ANTE UP 25 chips to start playing.", "Ante Up", JOptionPane.OK_OPTION);
        e = new BlackJackGameEngine();
        jTextField4.setText(String.valueOf(c));
    }

    public void paint(Graphics g){
        super.paint(g);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        DealerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        ButtonPanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jButton4.setText("Bet");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DealerPanel.setMinimumSize(new java.awt.Dimension(100, 50));
        DealerPanel.setPreferredSize(new java.awt.Dimension(556, 30));

        jLabel2.setText("Dealer Total:");
        DealerPanel.add(jLabel2);

        jTextField2.setPreferredSize(new java.awt.Dimension(50, 30));
        DealerPanel.add(jTextField2);

        getContentPane().add(DealerPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 599, -1));

        ButtonPanel.setMinimumSize(new java.awt.Dimension(100, 50));
        ButtonPanel.setPreferredSize(new java.awt.Dimension(556, 50));

        jButton1.setText("Hit");
        jButton1.setEnabled(false);
        ButtonPanel.add(jButton1);

        jButton2.setText("Stay");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButton2);

        jSlider1.setMajorTickSpacing(25);
        jSlider1.setMaximum(500);
        jSlider1.setPaintTicks(true);
        jSlider1.setSnapToTicks(true);
        jSlider1.setValue(25);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        ButtonPanel.add(jSlider1);

        jButton5.setBackground(new java.awt.Color(255, 255, 0));
        jButton5.setText("ANTE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        ButtonPanel.add(jButton5);

        jLabel1.setText("Chips:");
        ButtonPanel.add(jLabel1);

        jTextField1.setText("25");
        jTextField1.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField1.setPreferredSize(new java.awt.Dimension(50, 30));
        ButtonPanel.add(jTextField1);

        jLabel4.setText("Total:");
        ButtonPanel.add(jLabel4);

        jTextField4.setText("0");
        jTextField4.setMinimumSize(new java.awt.Dimension(20, 20));
        jTextField4.setPreferredSize(new java.awt.Dimension(50, 30));
        ButtonPanel.add(jTextField4);

        getContentPane().add(ButtonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 374, 730, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 150));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 740, 130));

        jPanel1.setBackground(new java.awt.Color(0, 204, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 150));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 740, 130));

        jPanel4.setPreferredSize(new java.awt.Dimension(600, 30));

        jLabel3.setText("Player Total:");
        jPanel4.add(jLabel3);

        jTextField3.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel4.add(jTextField3);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 600, 60));

        jMenu1.setText("File");

        jMenuItem1.setText("Start Playing");
        jMenuItem1.setEnabled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void beginPlay() throws IOException{
        Card[] dealerHand = new Card[5];
        Card[] playerHand = new Card[5];
        
        BlackJackDeck deck = null;
        try {
            deck = new BlackJackDeck();
        } catch (IOException ex) {
            Logger.getLogger(BlackJackFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        deck.shuffle();
        for(int i = 0; i < 2; i++){
            dealerHand[i] = deck.deal();
        }
        
        for(int i = 0; i < 2; i++){
            playerHand[i] = deck.deal();
        }
        
        //JLabel dealerCard1 = new JLabel(new ImageIcon(dealerHand[0].getCardImage()));
        JLabel dealerCard1 = new JLabel(new ImageIcon(Card.getFlippedCardImage()));
        JLabel dealerCard2 = new JLabel(new ImageIcon(dealerHand[1].getCardImage()));
        
        JLabel playerCard1 = new JLabel(new ImageIcon(playerHand[0].getCardImage()));
        JLabel playerCard2 = new JLabel(new ImageIcon(playerHand[1].getCardImage()));
        
        jPanel2.add(dealerCard1);
        jPanel2.add(dealerCard2);
        jPanel1.add(playerCard1);
        jPanel1.add(playerCard2);
        
        jTextField2.setText(String.valueOf(dealerHand[1].getCardValue()));
        jTextField3.setText(String.valueOf(playerHand[0].getCardValue() + playerHand[1].getCardValue()));

        
        
        repaint();
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
//        try {
//            // TODO add your handling code here:
//            beginPlay();
//            
//        } catch (IOException ex) {
//            Logger.getLogger(BlackJackFrame.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        jTextField1.setText(String.valueOf(jSlider1.getValue()));
    }//GEN-LAST:event_jSlider1StateChanged
    
    int userBet;
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    Card[][] initialDeal;
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        userBet = jSlider1.getValue();
        if(userBet >= 25){
            System.out.println("in here");
            e.didAnteUp(true);
            jButton5.setEnabled(false);
            try {
                initialDeal = e.beginPlay();
                //System.out.println(initialDeal[0][0]);
                JLabel dealerCard0 = new JLabel(new ImageIcon(Card.getFlippedCardImage()));
                JLabel dealerCard1 = new JLabel(new ImageIcon(initialDeal[0][1].getCardImage()));

                JLabel playerCard0 = new JLabel(new ImageIcon(initialDeal[1][0].getCardImage()));
                JLabel playerCard1 = new JLabel(new ImageIcon(initialDeal[1][1].getCardImage()));
                
                jPanel2.add(dealerCard0);
                jPanel2.add(dealerCard1);
                jPanel1.add(playerCard0);
                jPanel1.add(playerCard1);

                jPanel1.doLayout();
                jPanel2.doLayout();
                
                jTextField2.setText(String.valueOf(initialDeal[0][1].getCardValue()));
                jTextField3.setText(String.valueOf(initialDeal[1][0].getCardValue() + initialDeal[1][1].getCardValue()));
                
                jButton1.setEnabled(true);
                jButton2.setEnabled(true);
                
                
            } catch (IOException ex) {
                Logger.getLogger(BlackJackFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJackFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJackFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJackFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJackFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackJackFrame().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonPanel;
    private javax.swing.JPanel DealerPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
