/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Desktop;
import java.net.URL;

/**
 *
 * @author Perry
 */
public class HelpScreen extends javax.swing.JFrame {

    /**
     * Creates new form HelpScreen
     */
    public HelpScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BlackJackHelpButton = new javax.swing.JButton();
        FiveCardHelpButton = new javax.swing.JButton();
        HoldEmHelpButton = new javax.swing.JButton();
        RouletteHelpButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BlackJackHelpButton.setText("BlackJack");
        BlackJackHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlackJackHelpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BlackJackHelpButton);

        FiveCardHelpButton.setText("5 Card Poker");
        FiveCardHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiveCardHelpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(FiveCardHelpButton);

        HoldEmHelpButton.setText("Texas Hold'em");
        HoldEmHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoldEmHelpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(HoldEmHelpButton);

        RouletteHelpButton.setText("Roulette");
        RouletteHelpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RouletteHelpButtonActionPerformed(evt);
            }
        });
        jPanel1.add(RouletteHelpButton);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // roulette
    private void FiveCardHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiveCardHelpButtonActionPerformed
        // TODO add your handling code here:
        String urlString = "https://www.pokernews.com/strategy/5-card-draw-rules-how-to-play-five-card-draw-poker-23741.htm";
     try {
        Desktop.getDesktop().browse(new URL(urlString).toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_FiveCardHelpButtonActionPerformed
    
    private void BlackJackHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlackJackHelpButtonActionPerformed
        // TODO add your handling code here:
        String urlString = "https://www.hoylegaming.com/rules/showrule.aspx?RuleID=202";
     try {
        Desktop.getDesktop().browse(new URL(urlString).toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_BlackJackHelpButtonActionPerformed
   
    private void HoldEmHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoldEmHelpButtonActionPerformed
        // TODO add your handling code here:
         String urlString = "http://www.pokerlistings.com/poker-rules-texas-holdem";
           
     try {
        Desktop.getDesktop().browse(new URL(urlString).toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_HoldEmHelpButtonActionPerformed
   
    private void RouletteHelpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RouletteHelpButtonActionPerformed
        // TODO add your handling code here:
               String urlString = "http://www.rouletteonline.net/how-to-play-roulette/";
     try {
        Desktop.getDesktop().browse(new URL(urlString).toURI());
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_RouletteHelpButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlackJackHelpButton;
    private javax.swing.JButton FiveCardHelpButton;
    private javax.swing.JButton HoldEmHelpButton;
    private javax.swing.JButton RouletteHelpButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
