/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.RouletteEngine;
import Model.Player;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.security.SecureRandom;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Natalie
 */
public class RouletteFrame extends javax.swing.JFrame {

    //Variable to store the incoming Player obj, p
    public static Player p;
    
    /**
     * Creates new form RouletteFrame
     */
    public RouletteFrame() {
        initComponents();   //Configure all components of frame
        jLabel2.setText(String.valueOf(Player.currency));   //Set the currency label to show the player's currency
    }
    
    public static void startIt(Player player, boolean x) throws IOException {
        RouletteFrame.main(null);   //Run the main method
        p = player; //Store in variable p
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        button6 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        button12 = new java.awt.Button();
        button13 = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        button43 = new java.awt.Button();
        button44 = new java.awt.Button();
        button45 = new java.awt.Button();
        button46 = new java.awt.Button();
        button47 = new java.awt.Button();
        button48 = new java.awt.Button();
        button49 = new java.awt.Button();
        button50 = new java.awt.Button();
        button51 = new java.awt.Button();
        button52 = new java.awt.Button();
        button53 = new java.awt.Button();
        button54 = new java.awt.Button();
        button55 = new java.awt.Button();
        jPanel3 = new javax.swing.JPanel();
        button57 = new java.awt.Button();
        button58 = new java.awt.Button();
        button59 = new java.awt.Button();
        button60 = new java.awt.Button();
        button61 = new java.awt.Button();
        button62 = new java.awt.Button();
        button63 = new java.awt.Button();
        button64 = new java.awt.Button();
        button65 = new java.awt.Button();
        button66 = new java.awt.Button();
        button67 = new java.awt.Button();
        button68 = new java.awt.Button();
        button69 = new java.awt.Button();
        jPanel4 = new javax.swing.JPanel();
        textField1 = new java.awt.TextField();
        button15 = new java.awt.Button();
        button16 = new java.awt.Button();
        button17 = new java.awt.Button();
        button18 = new java.awt.Button();
        button19 = new java.awt.Button();
        button20 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width,Toolkit.getDefaultToolkit().getScreenSize().height - 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height / 4));
        jPanel1.setLayout(new java.awt.GridLayout());

        button1.setBackground(new java.awt.Color(0, 102, 0));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setLabel("0");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1);

        button2.setBackground(new java.awt.Color(255, 0, 0));
        button2.setForeground(new java.awt.Color(255, 255, 255));
        button2.setLabel("3");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2);

        button3.setBackground(new java.awt.Color(0, 0, 0));
        button3.setForeground(new java.awt.Color(255, 255, 255));
        button3.setLabel("6");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        jPanel1.add(button3);

        button4.setBackground(new java.awt.Color(255, 0, 0));
        button4.setForeground(new java.awt.Color(255, 255, 255));
        button4.setLabel("9");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        jPanel1.add(button4);

        button5.setBackground(new java.awt.Color(255, 0, 0));
        button5.setForeground(new java.awt.Color(255, 255, 255));
        button5.setLabel("12");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        jPanel1.add(button5);

        button6.setBackground(new java.awt.Color(0, 0, 0));
        button6.setForeground(new java.awt.Color(255, 255, 255));
        button6.setLabel("15");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        jPanel1.add(button6);

        button7.setBackground(new java.awt.Color(255, 0, 0));
        button7.setForeground(new java.awt.Color(255, 255, 255));
        button7.setLabel("18");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        jPanel1.add(button7);

        button8.setBackground(new java.awt.Color(255, 0, 0));
        button8.setForeground(new java.awt.Color(255, 255, 255));
        button8.setLabel("21");
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        jPanel1.add(button8);

        button9.setBackground(new java.awt.Color(0, 0, 0));
        button9.setForeground(new java.awt.Color(255, 255, 255));
        button9.setLabel("24");
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        jPanel1.add(button9);

        button10.setBackground(new java.awt.Color(255, 0, 0));
        button10.setForeground(new java.awt.Color(255, 255, 255));
        button10.setLabel("27");
        button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button10ActionPerformed(evt);
            }
        });
        jPanel1.add(button10);

        button11.setBackground(new java.awt.Color(255, 0, 0));
        button11.setForeground(new java.awt.Color(255, 255, 255));
        button11.setLabel("30");
        button11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button11ActionPerformed(evt);
            }
        });
        jPanel1.add(button11);

        button12.setBackground(new java.awt.Color(0, 0, 0));
        button12.setForeground(new java.awt.Color(255, 255, 255));
        button12.setLabel("33");
        button12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button12ActionPerformed(evt);
            }
        });
        jPanel1.add(button12);

        button13.setBackground(new java.awt.Color(255, 0, 0));
        button13.setForeground(new java.awt.Color(255, 255, 255));
        button13.setLabel("36");
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        jPanel1.add(button13);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height / 4));
        jPanel2.setLayout(new java.awt.GridLayout());

        button43.setBackground(new java.awt.Color(0, 102, 0));
        button43.setForeground(new java.awt.Color(255, 255, 255));
        button43.setLabel("0");
        button43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button43ActionPerformed(evt);
            }
        });
        jPanel2.add(button43);

        button44.setBackground(new java.awt.Color(0, 0, 0));
        button44.setForeground(new java.awt.Color(255, 255, 255));
        button44.setLabel("2");
        button44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button44ActionPerformed(evt);
            }
        });
        jPanel2.add(button44);

        button45.setBackground(new java.awt.Color(255, 0, 0));
        button45.setForeground(new java.awt.Color(255, 255, 255));
        button45.setLabel("5");
        button45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button45ActionPerformed(evt);
            }
        });
        jPanel2.add(button45);

        button46.setBackground(new java.awt.Color(0, 0, 0));
        button46.setForeground(new java.awt.Color(255, 255, 255));
        button46.setLabel("8");
        button46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button46ActionPerformed(evt);
            }
        });
        jPanel2.add(button46);

        button47.setBackground(new java.awt.Color(0, 0, 0));
        button47.setForeground(new java.awt.Color(255, 255, 255));
        button47.setLabel("11");
        button47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button47ActionPerformed(evt);
            }
        });
        jPanel2.add(button47);

        button48.setBackground(new java.awt.Color(255, 0, 0));
        button48.setForeground(new java.awt.Color(255, 255, 255));
        button48.setLabel("14");
        button48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button48ActionPerformed(evt);
            }
        });
        jPanel2.add(button48);

        button49.setBackground(new java.awt.Color(0, 0, 0));
        button49.setForeground(new java.awt.Color(255, 255, 255));
        button49.setLabel("17");
        button49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button49ActionPerformed(evt);
            }
        });
        jPanel2.add(button49);

        button50.setBackground(new java.awt.Color(0, 0, 0));
        button50.setForeground(new java.awt.Color(255, 255, 255));
        button50.setLabel("20");
        button50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button50ActionPerformed(evt);
            }
        });
        jPanel2.add(button50);

        button51.setBackground(new java.awt.Color(255, 0, 0));
        button51.setForeground(new java.awt.Color(255, 255, 255));
        button51.setLabel("23");
        button51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button51ActionPerformed(evt);
            }
        });
        jPanel2.add(button51);

        button52.setBackground(new java.awt.Color(0, 0, 0));
        button52.setForeground(new java.awt.Color(255, 255, 255));
        button52.setLabel("26");
        button52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button52ActionPerformed(evt);
            }
        });
        jPanel2.add(button52);

        button53.setBackground(new java.awt.Color(0, 0, 0));
        button53.setForeground(new java.awt.Color(255, 255, 255));
        button53.setLabel("29");
        button53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button53ActionPerformed(evt);
            }
        });
        jPanel2.add(button53);

        button54.setBackground(new java.awt.Color(255, 0, 0));
        button54.setForeground(new java.awt.Color(255, 255, 255));
        button54.setLabel("32");
        button54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button54ActionPerformed(evt);
            }
        });
        jPanel2.add(button54);

        button55.setBackground(new java.awt.Color(0, 0, 0));
        button55.setForeground(new java.awt.Color(255, 255, 255));
        button55.setLabel("35");
        button55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button55ActionPerformed(evt);
            }
        });
        jPanel2.add(button55);

        jPanel3.setBackground(new java.awt.Color(255, 102, 204));
        jPanel3.setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height / 4));
        jPanel3.setLayout(new java.awt.GridLayout());

        button57.setBackground(new java.awt.Color(0, 102, 0));
        button57.setForeground(new java.awt.Color(255, 255, 255));
        button57.setLabel("0");
        button57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button57ActionPerformed(evt);
            }
        });
        jPanel3.add(button57);

        button58.setBackground(new java.awt.Color(255, 0, 0));
        button58.setForeground(new java.awt.Color(255, 255, 255));
        button58.setLabel("1");
        button58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button58ActionPerformed(evt);
            }
        });
        jPanel3.add(button58);

        button59.setBackground(new java.awt.Color(0, 0, 0));
        button59.setForeground(new java.awt.Color(255, 255, 255));
        button59.setLabel("4");
        button59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button59ActionPerformed(evt);
            }
        });
        jPanel3.add(button59);

        button60.setBackground(new java.awt.Color(255, 0, 0));
        button60.setForeground(new java.awt.Color(255, 255, 255));
        button60.setLabel("7");
        button60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button60ActionPerformed(evt);
            }
        });
        jPanel3.add(button60);

        button61.setBackground(new java.awt.Color(0, 0, 0));
        button61.setForeground(new java.awt.Color(255, 255, 255));
        button61.setLabel("10");
        button61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button61ActionPerformed(evt);
            }
        });
        jPanel3.add(button61);

        button62.setBackground(new java.awt.Color(0, 0, 0));
        button62.setForeground(new java.awt.Color(255, 255, 255));
        button62.setLabel("13");
        button62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button62ActionPerformed(evt);
            }
        });
        jPanel3.add(button62);

        button63.setBackground(new java.awt.Color(255, 0, 0));
        button63.setForeground(new java.awt.Color(255, 255, 255));
        button63.setLabel("16");
        button63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button63ActionPerformed(evt);
            }
        });
        jPanel3.add(button63);

        button64.setBackground(new java.awt.Color(255, 0, 0));
        button64.setForeground(new java.awt.Color(255, 255, 255));
        button64.setLabel("19");
        button64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button64ActionPerformed(evt);
            }
        });
        jPanel3.add(button64);

        button65.setBackground(new java.awt.Color(0, 0, 0));
        button65.setForeground(new java.awt.Color(255, 255, 255));
        button65.setLabel("22");
        button65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button65ActionPerformed(evt);
            }
        });
        jPanel3.add(button65);

        button66.setBackground(new java.awt.Color(255, 0, 0));
        button66.setForeground(new java.awt.Color(255, 255, 255));
        button66.setLabel("25");
        button66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button66ActionPerformed(evt);
            }
        });
        jPanel3.add(button66);

        button67.setBackground(new java.awt.Color(0, 0, 0));
        button67.setForeground(new java.awt.Color(255, 255, 255));
        button67.setLabel("28");
        button67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button67ActionPerformed(evt);
            }
        });
        jPanel3.add(button67);

        button68.setBackground(new java.awt.Color(0, 0, 0));
        button68.setForeground(new java.awt.Color(255, 255, 255));
        button68.setLabel("31");
        button68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button68ActionPerformed(evt);
            }
        });
        jPanel3.add(button68);

        button69.setBackground(new java.awt.Color(255, 0, 0));
        button69.setForeground(new java.awt.Color(255, 255, 255));
        button69.setLabel("34");
        button69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button69ActionPerformed(evt);
            }
        });
        jPanel3.add(button69);

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));
        jPanel4.setPreferredSize(new Dimension(Toolkit.getDefaultToolkit().getScreenSize().width, Toolkit.getDefaultToolkit().getScreenSize().height / 4 - 50));

        textField1.setEditable(false);
        textField1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });

        button15.setLabel("Spin!");
        button15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button15ActionPerformed(evt);
            }
        });

        button16.setLabel("10");
        button16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button16ActionPerformed(evt);
            }
        });

        button17.setLabel("5");
        button17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button17ActionPerformed(evt);
            }
        });

        button18.setLabel("25");
        button18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button18ActionPerformed(evt);
            }
        });

        button19.setLabel("100");
        button19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button19ActionPerformed(evt);
            }
        });

        button20.setLabel("50");
        button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button20ActionPerformed(evt);
            }
        });

        jLabel1.setText("Currency:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button15, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(button17, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(button16, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(button18, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(button20, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(button19, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(36, 36, 36))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(button20, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button18, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button19, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button17, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(button16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Main Menu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Desktop");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 896, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed
    
    int userValue;  //The value selected as bet amount
    int totalWager = 0; //The total amount the user has wagered this round (on all pockets together)
    Vector<Integer> userBets = new Vector<Integer>();   //Vector to store every user bet made
    Vector<Integer> userPlacements = new Vector<Integer>(); //Vector to store every user pocket selection
    
    private void button17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button17ActionPerformed
        // TODO add your handling code here:
        userValue = 5;  //User clicked 5 button, so set value to 5
    }//GEN-LAST:event_button17ActionPerformed

    private void button16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button16ActionPerformed
        // TODO add your handling code here:
        userValue = 10;
    }//GEN-LAST:event_button16ActionPerformed

    private void button18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button18ActionPerformed
        // TODO add your handling code here:
        userValue = 25;
    }//GEN-LAST:event_button18ActionPerformed

    private void button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button20ActionPerformed
        // TODO add your handling code here:
        userValue = 50;
    }//GEN-LAST:event_button20ActionPerformed

    private void button19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button19ActionPerformed
        // TODO add your handling code here:
        userValue = 100;
    }//GEN-LAST:event_button19ActionPerformed

    /*  In each buttonXActionPerformed() method below,
        the system first checks that the user has selected a bet amount (userValue).
        Then, it checks that the user's currency exceeds the smallest possible bet amount (ensuring they can play).
        If both conditions are met, then the system adds the pocket choice and bet to respective vectors.
        The totalWager variable is incremented by the userValue bet amount
        The currency label is updated to reflect the bet.
        Finally the pocket clicked is grayed out to signal that it has already been selected.
    */
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(0);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button1.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button1ActionPerformed

    private void button43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button43ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(0);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button43.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button43ActionPerformed

    private void button57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button57ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(0);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button57.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button57ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(3);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button2.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button2ActionPerformed

    private void button44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button44ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(2);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button44.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button44ActionPerformed

    private void button58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button58ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(1);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button58.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button58ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(6);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button3.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void button45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button45ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(5);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button45.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button45ActionPerformed

    private void button59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button59ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(4);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button59.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button59ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(9);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button4.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button4ActionPerformed

    private void button46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button46ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(8);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button46.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button46ActionPerformed

    private void button60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button60ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(7);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button60.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button60ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(12);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button5.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button5ActionPerformed

    private void button61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button61ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(10);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button61.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button61ActionPerformed

    private void button47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button47ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(11);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button47.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button47ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(15);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button6.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button6ActionPerformed

    private void button48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button48ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(14);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button48.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button48ActionPerformed

    private void button62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button62ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(13);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button62.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button62ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(18);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button7.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button7ActionPerformed

    private void button49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button49ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(17);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button49.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button49ActionPerformed

    private void button63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button63ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(16);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button63.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button63ActionPerformed

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(21);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button8.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button8ActionPerformed

    private void button50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button50ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(20);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button50.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button50ActionPerformed

    private void button64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button64ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(19);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button64.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button64ActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(24);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button9.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button9ActionPerformed

    private void button51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button51ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(23);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button51.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button51ActionPerformed

    private void button65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button65ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(22);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button65.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button65ActionPerformed

    private void button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button10ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(27);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button10.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button10ActionPerformed

    private void button52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button52ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(26);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button52.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button52ActionPerformed

    private void button66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button66ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(25);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button66.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button66ActionPerformed

    private void button11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button11ActionPerformed
        // TODO add your handling code here:
        
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(30);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button11.setBackground(new Color(204,204,204));   
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button11ActionPerformed

    private void button53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button53ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(29);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button53.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button53ActionPerformed

    private void button67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button67ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(28);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button67.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button67ActionPerformed

    private void button12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button12ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(33);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button12.setBackground(new Color(204,204,204));  
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button12ActionPerformed

    private void button54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button54ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(32);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button54.setBackground(new Color(204,204,204));     
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button54ActionPerformed

    private void button68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button68ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(31);
            userBets.add(userValue);
            totalWager += userValue;
            jLabel2.setText(String.valueOf(Player.currency - totalWager));
            button68.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button68ActionPerformed

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(36);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button13.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button13ActionPerformed

    private void button55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button55ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(35);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button55.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button55ActionPerformed

    private void button69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button69ActionPerformed
        // TODO add your handling code here:
        if(userValue > 0){
            if(Player.currency > 5){
                userPlacements.add(34);
                userBets.add(userValue);
                totalWager += userValue;
                jLabel2.setText(String.valueOf(Player.currency - totalWager));
                button69.setBackground(new Color(204,204,204));
            } else {
                JOptionPane.showMessageDialog(null, "Please re-enter the casino.  You're out of money.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please click a chip value button towards the bottom of the screen to bet.");
        }
    }//GEN-LAST:event_button69ActionPerformed

    int winningPocket;  //To hold the randomly-generated winning value
    int userWinnings = 0;   //The amount the user wins (0 for now)
    private void button15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button15ActionPerformed
        // TODO add your handling code here:
        Player.currency -= totalWager;  //Subtract the total wager from the player's currency
        SecureRandom r = new SecureRandom();    //New random object
        winningPocket = r.nextInt(37);  //Generate new random integer from 0 to 36; assign to winningPocket
        textField1.setText(String.valueOf(winningPocket));  //Update textbox to show winningPocket
        RouletteEngine re = new RouletteEngine();   //Instantiate new RouletteEngine
        userWinnings = re.getWinner(userPlacements, userBets, winningPocket);   //Utilize getWinner() method and return the win amount
        Player.currency += userWinnings;    //Add the won amount to player's static currency
        if(userWinnings > 0){   //If the user won, notify a win.  If lost, notify a loss
            JOptionPane.showMessageDialog(null, "You won!");
        } else {
            JOptionPane.showMessageDialog(null, "Sorry, you lost.");
        }
        textField1.setText(""); //Clear winning number field
        
        //Reset all buttons to original background colors
        button1.setBackground(new Color(0,102,0));
        button2.setBackground(new Color(255,0,0));
        button3.setBackground(new Color(0,0,0));
        button4.setBackground(new Color(255,0,0));
        button5.setBackground(new Color(255,0,0));
        button6.setBackground(new Color(0,0,0));
        button7.setBackground(new Color(255,0,0));
        button8.setBackground(new Color(255,0,0));
        button9.setBackground(new Color(0,0,0));
        button10.setBackground(new Color(255,0,0));
        button11.setBackground(new Color(255,0,0));
        button12.setBackground(new Color(0,0,0));
        button13.setBackground(new Color(255,0,0));
        
        button43.setBackground(new Color(0,102,0));
        button44.setBackground(new Color(0,0,0));
        button45.setBackground(new Color(255,0,0));
        button46.setBackground(new Color(0,0,0));
        button47.setBackground(new Color(0,0,0));
        button48.setBackground(new Color(255,0,0));
        button49.setBackground(new Color(0,0,0));
        button50.setBackground(new Color(0,0,0));
        button51.setBackground(new Color(255,0,0));
        button52.setBackground(new Color(0,0,0));
        button53.setBackground(new Color(0,0,0));
        button54.setBackground(new Color(255,0,0));
        button55.setBackground(new Color(0,0,0));
        
        button57.setBackground(new Color(0,102,0));
        button58.setBackground(new Color(255,0,0));
        button59.setBackground(new Color(0,0,0));
        button60.setBackground(new Color(255,0,0));
        button61.setBackground(new Color(0,0,0));
        button62.setBackground(new Color(0,0,0));
        button63.setBackground(new Color(255,0,0));
        button64.setBackground(new Color(255,0,0));
        button65.setBackground(new Color(0,0,0));
        button66.setBackground(new Color(255,0,0));
        button67.setBackground(new Color(0,0,0));
        button68.setBackground(new Color(0,0,0));
        button69.setBackground(new Color(255,0,0));
        
        //Clear both vectors for next round to ensue
        userPlacements.clear();
        userBets.clear();
    }//GEN-LAST:event_button15ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        GameSelectionFrame.startIt(p);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RouletteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RouletteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RouletteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RouletteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RouletteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button15;
    private java.awt.Button button16;
    private java.awt.Button button17;
    private java.awt.Button button18;
    private java.awt.Button button19;
    private java.awt.Button button2;
    private java.awt.Button button20;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button43;
    private java.awt.Button button44;
    private java.awt.Button button45;
    private java.awt.Button button46;
    private java.awt.Button button47;
    private java.awt.Button button48;
    private java.awt.Button button49;
    private java.awt.Button button5;
    private java.awt.Button button50;
    private java.awt.Button button51;
    private java.awt.Button button52;
    private java.awt.Button button53;
    private java.awt.Button button54;
    private java.awt.Button button55;
    private java.awt.Button button57;
    private java.awt.Button button58;
    private java.awt.Button button59;
    private java.awt.Button button6;
    private java.awt.Button button60;
    private java.awt.Button button61;
    private java.awt.Button button62;
    private java.awt.Button button63;
    private java.awt.Button button64;
    private java.awt.Button button65;
    private java.awt.Button button66;
    private java.awt.Button button67;
    private java.awt.Button button68;
    private java.awt.Button button69;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables
}
